package view;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class ApplicationView {
    public static String accountNumberMenu() {
        return "Enter Account Number: ";
    }

    public static String pinMenu() {
        return "Enter PIN: ";
    }

    public static String transactionMenu() {
        return "\n" + "1. Withdraw\n" +
                "2. Fund Transfer\n" +
                "3. Exit\n" +
                "Please choose option[3]: ";
    }

    public static String withdrawMenu() {
        return "\n" + "1. $10\n" +
                "2. $50\n" +
                "3. $100\n" +
                "4. Other\n" +
                "5. Back\n" +
                "Please choose option[5]: ";
    }

    public static String otherWithdrawMenu() {
        return "\n" + "Other Withdraw\n" +
                "Enter amount to withdraw: $";
    }

    public static String fundTransferAccountMenu() {
        return "\n" + "Please enter destination account and \n" +
                "press enter to continue or \n" +
                "press cancel (Esc) to go back to Transaction: ";
    }

    public static String fundTransferAmountMenu() {
        return "\n" + "Please enter transfer amount and press enter to continue or \n" +
                "press enter to go back to Transaction: $";
    }

    public static String fundTransferReferenceMenu() {
        return "\n" + "Reference Number: (This is an autogenerated random 6 digits number)\n" +
                "press enter to continue or press enter to go back to Transaction: ";
    }

    public static String fundTransferConfirmationMenu(String accountNumber, String amount, String referenceNumber) {
        return "Transfer Confirmation\n" +
                "Destination Account : " + accountNumber + "\n" +
                "Transfer Amount     : $" + amount + "\n" +
                "Reference Number    : " + referenceNumber + "\n" +
                "\n" +
                "1. Confirm Transaction\n" +
                "2. Cancel Transaction\n" +
                "Choose option[2]: ";
    }

    public static String summaryMenu(String amount, String balance) {
        String date = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm a"));

        return "\n" + "Summary\n" +
                "Date : " + date + "\n" +
                "Withdraw : $" + amount + "\n" +
                "Balance : $" + balance + "\n" +
                "\n" +
                "1. Transaction \n" +
                "2. Exit\n" +
                "Choose option[2]:";
    }
}
