import entity.Transaction;
import repository.AccountRepository;
import repository.TransactionRepository;
import service.AccountService;
import service.TransactionService;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Scanner;

import static util.Validator.*;

public class Application {
    private static final Scanner scanner = new Scanner(System.in);
    private static AccountService accountService;
    private static TransactionService transactionService;

    public static void main(String[] args) {
        String filePath = args.length != 0 ? args[0] : "./data.csv";
        accountService = new AccountService(new AccountRepository(filePath));
        transactionService = new TransactionService(new TransactionRepository(), accountService);

        while (true) {
            welcomeScreen();
            break;
        }
    }

    public static void welcomeScreen() {
        while (true) {
            System.out.print("Enter Account Number: ");
            String accountNumber = scannerLogin(scanner, 6, "Account Number");
            System.out.print("Enter PIN: ");
            String pin = scannerLogin(scanner, 6, "PIN");

            if (accountService.login(accountNumber, pin)) {
                transactionScreen();
            }

            System.out.println("Invalid Account Number/PIN");
        }
    }

    public static void transactionScreen() {
        String message = "\n" + "1. Withdraw\n" +
                "2. Fund Transfer\n" +
                "3. Transaction History\n" +
                "4. Exit\n" +
                "Please choose option[4]: ";

        while (true) {
            System.out.print(message);

            String option = scannerOption(scanner, 1, 3, message);
            switch (option) {
                case "1" -> withdrawScreen();
                case "2" -> fundTransferScreen();
                case "3" -> transactionHistoryScreen();
                default -> welcomeScreen();
            }
        }
    }

    public static void withdrawScreen() {
        String message = "\n" + "1. $10\n" +
                "2. $50\n" +
                "3. $100\n" +
                "4. Other\n" +
                "5. Back\n" +
                "Please choose option[5]: ";

        while (true) {
            System.out.print(message);

            String option = scannerOption(scanner, 1, 5, message);
            switch (option) {
                case "1" -> {
                    if (transactionService.withdraw(10)) {
                        summaryScreen("10");
                    }
                }
                case "2" -> {
                    if (transactionService.withdraw(50)) {
                        summaryScreen("50");
                    }
                }
                case "3" -> {
                    if (transactionService.withdraw(100)) {
                        summaryScreen("100");
                    }
                }
                case "4" -> otherWithdrawScreen();
                default -> transactionScreen();
            }
        }
    }

    public static void otherWithdrawScreen() {
        String message = "\n" + "Other Withdraw\n" +
                "Enter amount to withdraw: $";

        while (true) {
            System.out.print(message);
            String amount = scannerAmount(scanner, 10, 1000, message);
            if (transactionService.withdraw(Integer.parseInt(amount))) {
                summaryScreen(amount);
            }
        }
    }

    public static void fundTransferScreen() {
        String message1 = "\n" + "Please enter destination account and \n" +
                "press enter to continue or \n" +
                "press cancel (Esc) to go back to Transaction: ";
        String message2 = "\n" + "Please enter transfer amount and press enter to continue or \n" +
                "press enter to go back to Transaction: $";
        String message3 = "\n" + "Reference Number: (This is an autogenerated random 6 digits number)\n" +
                "press enter to continue or press enter to go back to Transaction: ";


        while (true) {
            System.out.print(message1);
            String accountNumber = scannerTransferAccount(scanner, 6, message1);

            System.out.print(message2);
            String amount = scannerTransferAmount(scanner, 1, 1000, message2);

            System.out.print(message3);
            String referenceNumber = scannerTransferReference(scanner, 6, message3);


            String message4 = "\n" + "Transfer Confirmation\n" +
                    "Destination Account : " + accountNumber + "\n" +
                    "Transfer Amount     : $" + amount + "\n" +
                    "Reference Number    : " + referenceNumber + "\n" +
                    "\n" +
                    "1. Confirm Trx\n" +
                    "2. Cancel Trx\n" +
                    "Choose option[2]: ";
            System.out.print(message4);
            String option = scannerOption(scanner, 1, 2, message4);
            if (option.equals("1") && transactionService.transfer(accountNumber, Integer.parseInt(amount))) {
                summaryScreen(amount);
            } else {
                transactionScreen();
            }
        }
    }

    public static void summaryScreen(String amount) {
        String message = "\n" + "Summary\n" +
                "Date : " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm a")) + "\n" +
                "Withdraw : $" + amount + "\n" +
                "Balance : $" + accountService.getLoggedAccount().getBalance() + "\n" +
                "\n" +
                "1. Transaction \n" +
                "2. Exit\n" +
                "Choose option[2]:";

        while (true) {
            System.out.print(message);

            String option = scannerOption(scanner, 1, 2, message);
            if (option.equals("1")) {
                transactionScreen();
            } else {
                welcomeScreen();
            }
        }
    }

    public static void transactionHistoryScreen() {
        String message = "\n" + "Transaction History\n" +
                String.format("%8s %8s %8s %5s %20s\n", "ID", "Type", "Source", "Amount", "Transaction Time") +
                showTransactionHistory(transactionService.getTransactionHistory(accountService.getLoggedAccount().getAccountNumber())) +
                "1. Transaction \n" +
                "2. Exit\n" +
                "Choose option[2]:";

        while (true) {
            System.out.println(message);
            String option = scannerOption(scanner, 1, 2, message);
            if (option.equals("1")) {
                transactionScreen();
            } else {
                welcomeScreen();
            }
        }
    }

    public static String showTransactionHistory(List<Transaction> transactions) {
        return transactions
                .stream()
                .map(Transaction::toString)
                .reduce("", (builder, transaction) -> builder + transaction);
    }
}
